version: '3.4'

services:
    ping_pong_thrift_server:
        build:
            context: .
            dockerfile: ./server/Dockerfile
        network_mode: host
        expose:
            - "5000"
        ports:
            - "0.0.0.0:5000:5000"
        volumes:
            - ./game/PingPongGame/PingPongGameServer:/game
            - ./thrift:/thrift
    
    ping_pong_thrift_client:
        build:
            context: .
            dockerfile: ./client/Dockerfile
        network_mode: host
        expose:
            - "5000"
        ports:
            - "0.0.0.0:5000:5000"
        volumes:
            - ./game/PingPongGame/PingPongGameClient:/game
            - ./thrift:/thrift
        stdin_open: true
        tty: true
